apiVersion: v1
kind: Service
metadata:
  name: zimbra-mysql
  namespace: default
  labels:
    app: zimbra-mysql
spec:
  ports:
  - port: 3306
    name: mysql
  clusterIP: None
  selector:
    app: zimbra-mysql
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zimbra-mysql
  namespace: default
spec:
  serviceName: zimbra-mysql
  replicas: 1
  selector:
    matchLabels:
      app: zimbra-mysql
  template:
    metadata:
      labels:
        app: zimbra-mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "ZimbraSecure2026"
        - name: MYSQL_DATABASE
          value: "zimbra"
        - name: MYSQL_USER
          value: "admin"
        - name: MYSQL_PASSWORD
          value: "ZimbraSecure2026"
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: mysql-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: standard
      resources:
        requests:
          storage: 5Gi
