apiVersion: v1
kind: Secret
metadata:
  name: aws-localstack-creds
  namespace: crossplane-system
type: Opaque
stringData:
  # Crossplane AWS provider expects INI-style credentials in the "creds" key.
  creds: |
    [default]
    aws_access_key_id = test
    aws_secret_access_key = test

