apiVersion: v1
kind: Secret
metadata:
  name: aws-creds
  namespace: crossplane-system
type: Opaque
stringData:
  # Crossplane AWS provider attend un fichier creds au format INI (LocalStack)
  creds: |
    [default]
    aws_access_key_id = test
    aws_secret_access_key = test

