apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: default
data:
  otel-config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
      hostmetrics:
        collection_interval: 60s
        scrapers:
          cpu:
          memory:
          network:
          disk:
      mysql:
        collection_interval: 60s
        endpoint: "${env:MYSQL_ENDPOINT}"
        username: "${env:MYSQL_USERNAME}"
        password: "${env:MYSQL_PASSWORD}"
      filelog:
        include: [ /var/log/*.log, /var/log/syslog ]
        start_at: end

    processors:
      memory_limiter:
        check_interval: 5s
        limit_mib: 400
      batch:
      resourcedetection:
        detectors: [env, system]
      resource:
        attributes:
          - key: service.name
            value: idp-zimbra-local
            action: upsert
          - key: deployment.environment
            value: local
            action: upsert

    exporters:
      otlp:
        endpoint: "ingest.eu.signoz.cloud:443"
        tls:
          insecure: false
        headers:
          "signoz-ingestion-key": "${env:SIGNOZ_INGESTION_KEY}"
        compression: gzip
        sending_queue:
          enabled: true
          queue_size: 1000
        retry_on_failure:
          enabled: true

    service:
      pipelines:
        metrics:
          receivers: [otlp, hostmetrics, mysql]
          processors: [memory_limiter, resourcedetection, resource, batch]
          exporters: [otlp]
        logs:
          receivers: [otlp, filelog]
          processors: [memory_limiter, resourcedetection, resource, batch]
          exporters: [otlp]
        traces:
          receivers: [otlp]
          processors: [memory_limiter, resourcedetection, resource, batch]
          exporters: [otlp]
