apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: default
data:
  otel-config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
      hostmetrics:
        collection_interval: 60s
        scrapers:
          cpu:
          memory:
          network:
          disk:
      mysql:
        collection_interval: 60s
        endpoint: "zimbra-mysql:3306"
        username: "root"
        password: "ZimbraSecure2026"
      filelog:
        include: [ /var/log/*.log, /var/log/syslog ]
        start_at: end

    processors:
      batch:
      resourcedetection:
        detectors: [env, system]

    exporters:
      otlp:
        endpoint: "ingest.eu.signoz.cloud:443"
        tls:
          insecure: false
        headers:
          "signoz-access-token": "${env:SIGNOZ_ACCESS_TOKEN}"

    service:
      pipelines:
        metrics:
          receivers: [otlp, hostmetrics, mysql]
          processors: [batch, resourcedetection]
          exporters: [otlp]
        logs:
          receivers: [otlp, filelog]
          processors: [batch, resourcedetection]
          exporters: [otlp]
        traces:
          receivers: [otlp]
          processors: [batch, resourcedetection]
          exporters: [otlp]